### ISSUE TITLE
Possible to move all addon contents to addons/scene_safe_multiplayer for easier integration into existing projects?

### ISSUE THREAD

**Issue by NatCracken** [TestSubject06/GodotSceneSafeMultiplayer#1]
I've been running face first into the node not found issues so I'm hoping your plugin will help fix it, but its a bit of a pain to integrate into an existing project as is. Would be it possible to move everything to addons/scene_safe_multiplayer? not just the code but licenses, examples, ect...

**Comment by TestSubject06** [comment]
So the format of the repository is modeled after a few other plugin projects I had looked at to get an understanding of how Godot asset library projects are structured. That's not to say it's a perfect solution by any stretch, but there are some things about how Git and GutHub work that would make it impossible to move _all_ of the files around. For example the gitignore, license, and readme all have to be in the root directory to work correctly.

I think the project.godot file similarly has to stay in the root directory to function properly as well.

The rest of the files could be moved into an example directory when I have a bit of time for sure, but they're also not really intended to be carried over.

The intention is for installers to uncheck all the files that aren't the addon folder, which is why there's a copy of the license and the readme included there.

**Comment by NatCracken** [comment]
Thank you for clarifying, I'll do what I can with this
